### PR TITLE
OTHER: update waf to 2.0.22

### PR DESCRIPTION
**Pull request by trofi**
Adds support for modern python-3.9.

### CODE REVIEW

**Comment by trofi** [comment]
@dsvensson WDYT? :)

**Comment by trofi** [comment]
[trying again] @dsvensson WDYT of merging it?

**Comment by dsvensson** [comment]
@trofi Welcome to the new @xmms2/core-contributers team! :tada:

**Comment by trofi** [comment]
Thank you! /me hits all the merge buttons.

**Pull request merged**
