### PR TITLE
buiding error

### PR DESCRIPTION
**Pull request by 12sunflowers**
configure stage is passed but at build stage i have error

```
freeartist@devuan:~/Downloads/MOD/xmms2/xmms2-devel-master/xmms2-devel$ ./waf build
doc/tutorial: 8ff8c66d (up-to-date) 
src/lib/s4: 3556b807 (up-to-date) 
Waf: Entering directory `/home/freeartist/Downloads/MOD/xmms2/xmms2-devel-master/xmms2-devel/_build_'
[ 22/299] Compiling src/lib/xmmsutils/utils_unix.c
[ 80/299] Compiling src/clients/launcher/xmms2-launcher.c
[ 93/299] Compiling src/clients/lib/perl/XMMSClientPlaylist.xs
[ 94/299] Compiling src/clients/lib/perl/XMMSClient.xs
[ 95/299] Compiling src/clients/lib/perl/XMMSClientResult.xs
[ 96/299] Compiling src/clients/lib/perl/XMMSClientCollection.xs
/bin/sh: 1: podselect: not found

/bin/sh: 1: podselect: not found

/bin/sh: 1: podselect: not found

/bin/sh: 1: podselect: not found

Waf: Leaving directory `/home/freeartist/Downloads/MOD/xmms2/xmms2-devel-master/xmms2-devel/_build_'
Build failed
 -> task in '' failed with exit status 127 (run with -v to display more information)
 -> task in '' failed with exit status 127 (run with -v to display more information)
 -> task in '' failed with exit status 127 (run with -v to display more information)
 -> task in '' failed with exit status 127 (run with -v to display more information)
freeartist@devuan:~/Downloads/MOD/xmms2/xmms2-devel-master/xmms2-devel$ 
```

```
freeartist@devuan:~/Downloads/MOD/xmms2/xmms2-devel-master/xmms2-devel$ ./waf build -v
doc/tutorial: 8ff8c66d (up-to-date) 
src/lib/s4: 3556b807 (up-to-date) 
Waf: Entering directory `/home/freeartist/Downloads/MOD/xmms2/xmms2-devel-master/xmms2-devel/_build_'
[ 19/299] Compiling src/xmms/builtin_plugins.genpy
01:24:47 runner ' /usr/bin/python ../src/xmms/builtin_plugins.genpy equalizer replaygain > src/xmms/builtin_plugins.c '
[ 31/299] Compiling src/clients/lib/perl/XMMSClient.xs
01:24:47 runner ' podselect ../src/clients/lib/perl/XMMSClient.xs > src/clients/lib/perl/Audio/XMMSClient.pod '
[ 32/299] Compiling src/clients/lib/perl/XMMSClientResult.xs
01:24:47 runner ' podselect ../src/clients/lib/perl/XMMSClientResult.xs > src/clients/lib/perl/Audio/XMMSClient/Result.pod '
[ 33/299] Compiling src/clients/lib/perl/XMMSClientPlaylist.xs
01:24:47 runner ' podselect ../src/clients/lib/perl/XMMSClientPlaylist.xs > src/clients/lib/perl/Audio/XMMSClient/Playlist.pod '
[ 35/299] Compiling src/clients/lib/perl/XMMSClientCollection.xs
01:24:47 runner ' podselect ../src/clients/lib/perl/XMMSClientCollection.xs > src/clients/lib/perl/Audio/XMMSClient/Collection.pod '
/bin/sh: 1: podselect: not found

/bin/sh: 1: podselect: not found

/bin/sh: 1: podselect: not found

/bin/sh: 1: podselect: not found

Waf: Leaving directory `/home/freeartist/Downloads/MOD/xmms2/xmms2-devel-master/xmms2-devel/_build_'
Build failed
 -> task in '' failed with exit status 127: 
	{task 139824519825664: perldoc XMMSClient.xs -> XMMSClient.pod}
' podselect ../src/clients/lib/perl/XMMSClient.xs > src/clients/lib/perl/Audio/XMMSClient.pod '
 -> task in '' failed with exit status 127: 
	{task 139824519826000: perldoc XMMSClientResult.xs -> Result.pod}
' podselect ../src/clients/lib/perl/XMMSClientResult.xs > src/clients/lib/perl/Audio/XMMSClient/Result.pod '
 -> task in '' failed with exit status 127: 
	{task 139824519825776: perldoc XMMSClientPlaylist.xs -> Playlist.pod}
' podselect ../src/clients/lib/perl/XMMSClientPlaylist.xs > src/clients/lib/perl/Audio/XMMSClient/Playlist.pod '
 -> task in '' failed with exit status 127: 
	{task 139824519825888: perldoc XMMSClientCollection.xs -> Collection.pod}
' podselect ../src/clients/lib/perl/XMMSClientCollection.xs > src/clients/lib/perl/Audio/XMMSClient/Collection.pod '
freeartist@devuan:~/Downloads/MOD/xmms2/xmms2-devel-master/xmms2-devel$ 

```

### CODE REVIEW

**Comment by trofi** [comment]
Are you sure you picked correct target branch? Github sees 113 commits in this PR.

**Comment by trofi** [comment]
This pull request looks mangled. Can you redo it against current `master` branch so it contains only your added changes? I'll close this one. Please reopen it or create a new PR (whichever is simpler to you).

**Comment by trofi** [comment]
@dsvensson WDYT of opening issue tracking here on github? It would ease people to file reports like this one without the need to forge a PR. @hartwork would also like to file a few bugs.

**Comment by dsvensson** [comment]
...and perhaps delete this repo and rename xmms2-stable to xmms2? The -stable/-devel split has always felt like a hack because we didn't know git when starting using it one month old. I blame @wanders 😂

**Comment by trofi** [comment]
Sounds very reasonable :)

**Pull request closed without merging**
